=== NLCR/NDK-validator/utilities/src/main/resources/xsd/urnnbn_notification_response.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.logica.com/ndk/tm/urnnbn_notification_response" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.logica.com/ndk/tm/urnnbn_notification_response">

    <complexType name="URNNBNNotificationResponseType">
    	<sequence>
    		<element name="batchNumber" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="records" type="tns:Records" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="Records">
    	<sequence>
    		<element name="record" type="tns:Record" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
    
    <complexType name="Record">
    	<sequence>
    		<element name="docNumber" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="barCode" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="status" type="tns:Status" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="reason" type="string" maxOccurs="1" minOccurs="0"></element>
			<element name="uuid" type="string" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <element name="URNNBNNotificationResponse">
    	<complexType>
    		<complexContent>
    			<extension base="tns:URNNBNNotificationResponseType"/>
    		</complexContent>
    	</complexType>
    </element>

    <simpleType name="Status">
    	<restriction base="string">
    		<enumeration value="OK"></enumeration>
    		<enumeration value="ERROR"></enumeration>
    	</restriction>
    </simpleType>
</schema>

=== NLCR/NDK-validator/utilities/src/test/resources/com/logica/ndk/tm/utilities/integration/aleph/notification/urnnbn_notification_response.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:URNNBNNotificationResponse xmlns:tns="http://www.example.org/urnnbn_notification_response" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/urnnbn_notification_response urnnbn_notification_response.xsd ">
  <tns:batchNumber>2012_03_29_0001</tns:batchNumber>
  <tns:records>
    <tns:record>
      <tns:docNumber>000358463</tns:docNumber>
      <tns:barCode>1001240651</tns:barCode>
      <tns:status>ERROR</tns:status>
      <tns:reason>Invalid URL for digitalRecord 2</tns:reason>
	  <tns:uuid>c71af6e0-ae2d-11e1-952a-02004c4f4f50</tns:uuid>
    </tns:record>
    <tns:record>
    	<tns:docNumber>001701183</tns:docNumber>
    	<tns:barCode>1001519853</tns:barCode>
    	<tns:status>OK</tns:status>
		<tns:uuid>c71af6e0-ae2d-11e1-952a-02004c4f4f54</tns:uuid>
    </tns:record>
  </tns:records>
</tns:URNNBNNotificationResponse>
